const Apis = {
  status: true,
  message: "success",
  timestamp: new Date(),
  data: {
    india: [
      {
        id: 1,
        country: "India",
        hotels: ["radisson", "Taj", "Badrinath", "dayal"],
        images: "",
        hotelPrice: "200",
        state: "",
        tour: "",
        travelTickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 2,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 3,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 4,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 5,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 6,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 7,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 8,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 9,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 10,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 11,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 12,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 13,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 14,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 15,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 16,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      }
    ],
    Australia: [
      {
        id: 21,
        country: "India",
        hotels: ["radisson", "Taj", "Badrinath", "dayal"],
        images: "",
        hotelPrice: "200",
        state: "",
        tour: "",
        travelTickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 22,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 23,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 24,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      }
    ],
    Europe: [
      {
        id: 31,
        country: "India",
        hotels: ["radisson", "Taj", "Badrinath", "dayal"],
        images: "",
        hotelPrice: "200",
        state: "",
        tour: "",
        travelTickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 34,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 51,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 71,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 64,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      },
      {
        id: 41,
        country: "",
        hotels: "",
        images: "",
        price: "",
        state: "",
        tour: "",
        tickets: "",
        ratings: "",
        rentals: {},
        coupons: "",
        qrcode: "",
        dates: []
      }
    ]
  }
};
export default Apis;
